name: qpbenchmark
channels:
    - https://conda.anaconda.org/conda-forge
    - https://conda.anaconda.org/gurobi
dependencies:
    - clarabel >= 0.4.1
    - cvxopt >= 1.3.0
    - daqp >= 0.5.1
    - ecos >= 2.0.10
    - gurobi >= 11.0.3
    - ipython
    - jaxopt
    - kvxopt
    - matplotlib
    - numpy >= 1.25.2
    - osqp >= 0.6.2
    - pip
    - piqp >= 0.2.2
    - proxsuite >= 0.4.1
    - qpoases >= 3.2.0
    - quadprog >= 0.1.11
    - scs >= 3.2.2
    - pip:
        - highspy >= 1.5.2
        - qpalm >= 1.2.1
        - qpax
